# Generated by Django 3.2.6 on 2021-10-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('degree', models.PositiveSmallIntegerField(choices=[(0, 'Bacharelado'), (1, 'Licenciatura'), (2, 'Tecnológico'), (3, 'Sequencial')], default=0)),
                ('modality', models.PositiveSmallIntegerField(choices=[(0, 'Presencial'), (1, 'A Distância')], default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_ies', models.CharField(max_length=5)),
                ('nome_ies', models.CharField(max_length=20)),
                ('categoria_administrativa', models.CharField(max_length=20)),
                ('organização_academica', models.CharField(max_length=20)),
                ('situacao_ies', models.CharField(max_length=20)),
                ('duracao', models.IntegerField()),
                ('college_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.IntegerField(null=True)),
                ('Sigla_da_IES', models.CharField(max_length=500)),
                ('Nome_da_IES', models.CharField(max_length=500)),
                ('Categoria_Administrativa', models.CharField(max_length=500)),
                ('Organizacao_Academica', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso_teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.IntegerField()),
                ('codigo_ies', models.IntegerField()),
                ('sigla_ies', models.CharField(max_length=500)),
                ('nome_ies', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=25)),
                ('area_curso', models.CharField(max_length=25)),
                ('descricao_curso', models.TextField()),
                ('salario_estag', models.IntegerField()),
                ('salario_junior', models.IntegerField()),
                ('salario_pleno', models.IntegerField()),
                ('salario_senior', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14)),
                ('legal_nature', models.CharField(max_length=100)),
                ('legal_representative', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('ies', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=20)),
                ('admin_category', models.PositiveSmallIntegerField(choices=[(0, 'Pública Municipal'), (1, 'Pública Federal'), (2, 'Pública Estadual'), (3, 'Privada sem fins lucrativos'), (4, 'Privada com fins lucrativos'), (5, 'Privada beneficente'), (6, 'Especial')], default=4)),
                ('situation', models.PositiveSmallIntegerField(choices=[(0, 'Inativa'), (1, 'Ativa')], default=1)),
                ('academic_organization', models.PositiveSmallIntegerField(choices=[(0, 'Faculdade'), (1, 'Centro Universitário'), (2, 'Institutos Federais'), (3, 'Universidade')], default=0)),
                ('ci', models.PositiveSmallIntegerField(null=True)),
                ('year_ci', models.PositiveSmallIntegerField(null=True)),
                ('igc', models.PositiveSmallIntegerField(null=True)),
                ('year_igc', models.PositiveSmallIntegerField(null=True)),
                ('date_vest', models.DateField(null=True)),
                ('opening_date_entries', models.DateField(null=True)),
                ('closing_date_entries', models.DateField(null=True)),
                ('just_scheduling', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('number', models.PositiveSmallIntegerField()),
                ('complement', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('tel', models.CharField(max_length=11)),
                ('fax', models.CharField(max_length=11)),
                ('site', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='emec.maintainer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CoursesInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enade', models.PositiveSmallIntegerField(null=True)),
                ('cpc', models.PositiveSmallIntegerField(null=True)),
                ('uf', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emec.courses')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_inst', to='emec.institution')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_institution',
            field=models.ManyToManyField(related_name='courses_institution', through='emec.CoursesInstitution', to='emec.Institution'),
        ),
    ]
