# Generated by Django 3.2.6 on 2021-11-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courses_institution',
        ),
        migrations.RemoveField(
            model_name='coursesinstitution',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursesinstitution',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Curso_Faculdade',
        ),
        migrations.DeleteModel(
            name='Curso_teste',
        ),
        migrations.DeleteModel(
            name='Faculdade',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='maintainer',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='CoursesInstitution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Maintainer',
        ),
    ]
