# Generated by Django 3.2.6 on 2021-08-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_ies', models.CharField(max_length=5)),
                ('nome_ies', models.CharField(max_length=20)),
                ('categoria_administrativa', models.CharField(max_length=20)),
                ('organização_academica', models.CharField(max_length=20)),
                ('situacao_ies', models.CharField(max_length=20)),
            ],
        ),
    ]
