# Generated by Django 3.2.6 on 2021-08-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
