# Generated by Django 3.2.6 on 2021-08-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0002_curso_duracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=25)),
                ('area_curso', models.CharField(max_length=25)),
            ],
        ),
    ]
