# Generated by Django 3.2.6 on 2021-08-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0003_faculdade'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculdade',
            name='descricao_curso',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
