# Generated by Django 3.2.6 on 2021-08-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0004_faculdade_descricao_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculdade',
            name='salario_estag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculdade',
            name='salario_junior',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculdade',
            name='salario_pleno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculdade',
            name='salario_senior',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
