# Generated by Django 3.2.6 on 2021-08-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0009_auto_20210818_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso_faculdade',
            old_name='Bairro',
            new_name='Organizacao_Academica',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Carga_Horária',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Complemento',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Código_do_Endereço',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Endereço',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Grau',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Integralização_Turno_Integral',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Integralização_Turno_Matutino',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Integralização_Turno_Noturno',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Integralização_Turno_Vespertino',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Modalidade',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Nome_do_Campus',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Nome_do_Curso',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Número_Endereço',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Organização_Acadêmica',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Qt_Vagas_Autorizadas',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Quantitativo_de_Vagas_Integral',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Quantitativo_de_Vagas_Matutino',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Quantitativo_de_Vagas_Noturno',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Quantitativo_de_Vagas_Vespertino',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Sinalização_do_Curso',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Situação_do_Curso',
        ),
        migrations.RemoveField(
            model_name='curso_faculdade',
            name='Tipo_de_Periodicidade',
        ),
    ]
