# Generated by Django 3.2.6 on 2021-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0011_curso_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso_teste',
            name='codigo_curso',
            field=models.IntegerField(),
        ),
    ]
