# Generated by Django 3.2.6 on 2021-09-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0012_alter_curso_teste_codigo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso_teste',
            name='codigo_ies',
            field=models.IntegerField(),
        ),
    ]
