# Generated by Django 3.2.6 on 2021-10-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0014_auto_20211018_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='codigo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
