# Generated by Django 3.2.8 on 2021-10-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0014_auto_20211018_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
