# Generated by Django 3.2.8 on 2021-10-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0015_institution_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='title',
            field=models.CharField(default='Instituição', max_length=255),
        ),
    ]
