# Generated by Django 3.2.8 on 2021-10-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0019_alter_institution_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default='curso', max_length=200),
        ),
    ]
