# Generated by Django 3.2.8 on 2021-10-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0020_courses_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='title',
        ),
        migrations.AddField(
            model_name='courses',
            name='situation',
            field=models.CharField(default='Em análise', max_length=200),
        ),
    ]
