# Generated by Django 3.2.8 on 2021-10-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0021_auto_20211020_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesinstitution',
            name='name',
            field=models.CharField(default='Curso, Instituição', max_length=200),
        ),
    ]
