# Generated by Django 3.2.6 on 2021-10-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0015_courses_codigo'),
        ('buscacurso', '0023_alter_maintainer_name'),
    ]

    operations = [
    ]
