# Generated by Django 3.2.8 on 2021-10-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0024_merge_0015_courses_codigo_0023_alter_maintainer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Curso_Faculdade',
        ),
        migrations.DeleteModel(
            name='Curso_teste',
        ),
        migrations.DeleteModel(
            name='Faculdade',
        ),
    ]
