# Generated by Django 3.2.8 on 2021-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0025_auto_20211020_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_ies', models.CharField(max_length=5)),
                ('nome_ies', models.CharField(max_length=20)),
                ('categoria_administrativa', models.CharField(max_length=20)),
                ('organização_academica', models.CharField(max_length=20)),
                ('situacao_ies', models.CharField(max_length=20)),
                ('duracao', models.IntegerField()),
                ('college_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.IntegerField(null=True)),
                ('Sigla_da_IES', models.CharField(max_length=500)),
                ('Nome_da_IES', models.CharField(max_length=500)),
                ('Categoria_Administrativa', models.CharField(max_length=500)),
                ('Organizacao_Academica', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso_teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.IntegerField()),
                ('codigo_ies', models.IntegerField()),
                ('sigla_ies', models.CharField(max_length=500)),
                ('nome_ies', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=25)),
                ('area_curso', models.CharField(max_length=25)),
                ('descricao_curso', models.TextField()),
                ('salario_estag', models.IntegerField()),
                ('salario_junior', models.IntegerField()),
                ('salario_pleno', models.IntegerField()),
                ('salario_senior', models.IntegerField()),
            ],
        ),
    ]
