# Generated by Django 3.2.8 on 2021-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0026_curso_curso_faculdade_curso_teste_faculdade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='degree',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
