# Generated by Django 3.2.8 on 2021-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0027_alter_courses_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='modality',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
