# Generated by Django 3.2.8 on 2021-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0028_alter_courses_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='modality',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Presencial'), (1, 'A Distância')], default=1),
        ),
        migrations.AlterField(
            model_name='institution',
            name='admin_category',
            field=models.CharField(max_length=200),
        ),
    ]
