# Generated by Django 3.2.8 on 2021-11-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0029_auto_20211021_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
