# Generated by Django 3.2.8 on 2021-11-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0031_alter_courses_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default='-', max_length=250, null=True),
        ),
    ]
