# Generated by Django 3.2.8 on 2021-11-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0032_alter_courses_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='duration',
        ),
        migrations.AddField(
            model_name='coursesinstitution',
            name='duration',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
