# Generated by Django 3.2.8 on 2021-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0033_auto_20211105_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesinstitution',
            name='duration',
            field=models.CharField(default='-', max_length=250, null=True),
        ),
    ]
