# Generated by Django 3.2.6 on 2021-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0035_coursesdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesdescription',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
