# Generated by Django 3.2.6 on 2021-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0036_coursesdescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesdescription',
            name='name',
            field=models.CharField(default='Curso, Instituição', max_length=200),
        ),
    ]
