# Generated by Django 3.2.6 on 2021-11-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0038_alter_coursesdescription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesdescription',
            name='name',
        ),
    ]
