# Generated by Django 3.2.6 on 2021-11-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0039_remove_coursesdescription_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesdescription',
            old_name='course',
            new_name='code',
        ),
    ]
