# Generated by Django 3.2.6 on 2021-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0040_rename_course_coursesdescription_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdescription',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
