# Generated by Django 3.2.6 on 2021-11-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0041_alter_coursesdescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdescription',
            name='description',
            field=models.TextField(),
        ),
    ]
