# Generated by Django 3.2.6 on 2021-11-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0043_auto_20211107_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
