# Generated by Django 3.2.6 on 2021-11-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0043_auto_20211107_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Curso_Faculdade',
        ),
        migrations.DeleteModel(
            name='Curso_teste',
        ),
        migrations.DeleteModel(
            name='Faculdade',
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
