# Generated by Django 3.2.6 on 2021-11-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscacurso', '0044_auto_20211110_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='codigo',
        ),
    ]
